version: 2.1

orbs:
  maven: circleci/maven@0.0.12

executors:
  java-version:
    docker:
      - image: 'cimg/openjdk:11.0.7'

workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: java-version
